name: CI
on:
  push:
    branches: [main]
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up environment
        run: echo "Add language setup here (e.g. actions/setup-go, actions/setup-node)"
      - name: Lint
        run: echo "Add lint step here"
      - name: Test
        run: echo "Add test step here"
      - name: Build
        run: echo "Add build step here"
